services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    networks:
      - app_network
  registry-server:
    build:
      context: ./registry-server
    ports:
      - 3000:3000
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/registry?directConnection=true
    networks:
      - app_network
    depends_on:
      - mongodb
  relay-server:
    build:
      context: ./relay-server
    ports:
      - 1883:1883
    networks:
      - app_network
    depends_on:
      - registry-server
  body-server:
    build:
      context: ./body-server
    networks:
      - app_network
    depends_on:
      - relay-server
  control-panel:
    build:
      context: ./control-panel
    networks:
      - app_network
    ports:
      - 8000:8000
    depends_on:
      - registry-server

networks:
  app_network:
    driver: bridge
