services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - app_network

  registry-server:
    build:
      context: ./registry-server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:postgres@postgres:5432/registry"
    networks:
      - app_network
    depends_on:
      - postgres

  relay-server:
    build:
      context: ./relay-server
    ports:
      - "1883:1883"
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - registry-server

  control-panel:
    build:
      context: ./control-panel
    ports:
      - "8000:8000"
    depends_on:
      - registry-server

networks:
  app_network:
    driver: bridge
